=== Aion-Eternal-Team/aion-server-beyond/game-server/data/static_data/npc_skills/npc_skills.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="npc_skill_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="npcskills" type="NpcSkillList" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="NpcSkillList">
		<xs:sequence>
			<xs:element name="npcskill" type="NpcSkillTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npcid" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="NpcSkillTemplate">
		<xs:sequence>
			<xs:element name="cond" type="NpcSkillConditionTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="skillid" type="xs:int"/>
		<xs:attribute name="skilllevel" type="xs:int"/>
		<xs:attribute name="probability" type="xs:int"/>
		<xs:attribute name="maxhp" type="xs:int"/>
		<xs:attribute name="minhp" type="xs:int"/>
        <xs:attribute name="maxtime" type="xs:int"/>
		<xs:attribute name="mintime" type="xs:int"/>
        <xs:attribute name="conjunction" type="ConjunctionType"/>
        <xs:attribute name="cooldown" type="xs:int"/>
		<xs:attribute name="useinspawned" type="xs:boolean"/>
		<xs:attribute name="priority" type="xs:int"/>
		<xs:attribute name="nextSkillTime" type="xs:int"/>
		<xs:attribute name="nextChainId" type="xs:int"/>
		<xs:attribute name="chainId" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="NpcSkillConditionTemplate">
		<xs:attribute name="condType" type="ConditionType"/>
		<xs:attribute name="range" type="xs:int"/>
		<xs:attribute name="hpBelow" type="xs:int"/>
	</xs:complexType>
        <xs:simpleType name="ConjunctionType">
            <xs:restriction base="xs:string">
                <xs:enumeration value="AND"/>
                <xs:enumeration value="OR"/>
                <xs:enumeration value="XOR"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:simpleType name="ConditionType">
        	<xs:restriction base="xs:string">
        		<xs:enumeration value="NONE"/>
        		<xs:enumeration value="SELECT_RANDOM_ENEMY"/>
        		<xs:enumeration value="SELECT_RANDOM_ENEMY_EXCEPT_MOST_HATED"/>
        		<xs:enumeration value="HELP_FRIEND"/>
        		<xs:enumeration value="HELP_SELF"/>
        		<xs:enumeration value="TARGET_IS_IN_ANY_STUN"/>
        		<xs:enumeration value="TARGET_IS_IN_STUMBLE"/>
        		<xs:enumeration value="TARGET_IS_STUNNED"/>
        		<xs:enumeration value="TARGET_IS_SLEEPING"/>
        		<xs:enumeration value="TARGET_IS_AETHERS_HOLD"/>
        		<xs:enumeration value="TARGET_IS_POISONED"/>
        		<xs:enumeration value="TARGET_IS_BLEEDING"/>
        		<xs:enumeration value="TARGET_IS_GATE"/>
        		<xs:enumeration value="TARGET_IS_PLAYER"/>
        		<xs:enumeration value="TARGET_IS_PHYSICAL_CLASS"/>
        		<xs:enumeration value="TARGET_IS_MAGICAL_CLASS"/>
        		<xs:enumeration value="TARGET_HAS_CARVED_SIGNET"/>
        		<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_II"/>
        		<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_III"/>
        		<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_IV"/>
        		<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_V"/>
        	</xs:restriction>
        </xs:simpleType>
</xs:schema>

=== Aion-Eternal-Team/aion-server-beyond/game-server/data/static_data/npc_skills/skills/instances/300610000_Raksang_Ruins.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../npc_skills.xsd">
	<!-- Draconute Scout -->
	<npcskills npcid="236005">
		<npcskill skillid="21135" skilllevel="1" probability="100" useinspawned="true"/>
		<npcskill skillid="19430" skilllevel="56" probability="75"/>
		<npcskill skillid="17243" skilllevel="1" probability="33"/>
	</npcskills>
	<!-- Draconute Combatant -->
	<npcskills npcid="236006">
		<npcskill skillid="21135" skilllevel="1" probability="100" useinspawned="true"/>
		<npcskill skillid="16516" skilllevel="1" probability="75"/>
	</npcskills>
	<!-- Drill Camp Assasin -->
	<npcskills npcid="236007">
		<npcskill skillid="21135" skilllevel="1" probability="100" useinspawned="true"/>
		<npcskill skillid="17322" skilllevel="1" probability="50"/>
	</npcskills>
	<!-- Drill Camp Guard | Classified Drill Camp Instructor -->
	<npcskills npcid="236008 236084">
		<npcskill skillid="21135" skilllevel="1" probability="100" useinspawned="true"/>
		<npcskill skillid="17294" skilllevel="1" probability="80"/>
	</npcskills>
	<!-- Trained Vespine -->
	<npcskills npcid="236009">
		<npcskill skillid="20945" skilllevel="1" probability="25"/>
	</npcskills>
	<!-- Trained Porgus | Trained Worg | Crumbling Skelesword | Trained Fierce Lapilima | Trained Drakie -->
	<npcskills npcid="236010 236011 236012 236018 236021 236097">
		<npcskill skillid="21300" skilllevel="1" probability="40"/>
	</npcskills>
	<!-- Withering Husk -->
	<npcskills npcid="236013">
		<npcskill skillid="16825" skilllevel="1" probability="33"/>
	</npcskills>
	<!-- Ragelich Adept -->
	<npcskills npcid="236014">
		<npcskill skillid="19052" skilllevel="1" probability="14"/>
		<npcskill skillid="20944" skilllevel="36" probability="45"/>
		<npcskill skillid="16830" skilllevel="1" probability="100" maxhp="10"/>
	</npcskills>
	<!-- Trained Clodworm -->
	<npcskills npcid="236020 236096 236098">
		<npcskill skillid="17558" skilllevel="1" probability="67"/>
	</npcskills>
	<!-- Drill Instructor Diplito -->
	<npcskills npcid="236303">
		<npcskill skillid="21287" skilllevel="1" probability="100" maxhp="50" cooldown="30000"/>
		<npcskill skillid="17335" skilllevel="1" probability="75"/>
	</npcskills>
	<!-- Drill Instructor Pratica -->
	<npcskills npcid="236304">
		<npcskill skillid="16405" skilllevel="1" probability="100" cooldown="20000"/>
		<npcskill skillid="21285" skilllevel="1" probability="40"/>
		<npcskill skillid="22658" skilllevel="20" probability="33"/>
	</npcskills>
	<!-- Drill Instructor Exico -->
	<npcskills npcid="236305">
		<npcskill skillid="17048" skilllevel="1" probability="50"/>
		<!-- <npcskill skillid="21432" skilllevel="1" probability="100" maxhp="48" cooldown="60000"/> -->
	</npcskills>
	<!-- Reviver Nasto -->
	<npcskills npcid="236306">
		<npcskill skillid="16570" skilllevel="1" probability="66" cooldown="12000"/>
		<npcskill skillid="22106" skilllevel="1" probability="100" maxhp="66" cooldown="300000"/>
		<npcskill skillid="22106" skilllevel="1" probability="100" maxhp="33" cooldown="300000"/>
	</npcskills>
	<!-- Improved Thermitron -->
	<npcskills npcid="855852">
		<npcskill skillid="21534" skilllevel="1" probability="100"/>
	</npcskills>
	<!-- Skeleton Guard -->
	<npcskills npcid="855908">
		<npcskill skillid="16556" skilllevel="1" probability="25"/>
	</npcskills>
</npc_skill_templates>
